on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/**'

jobs:
  test-action:
    name: Test package creation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dsm: ["7.0"]
        arch: ["geminilake", "avoton"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare test packages
        run: |
          rm -rf src && git clone https://github.com/SynologyOpenSource/ExamplePackages src
      - name: Build Package with local action
        uses: ./
        with:
          dsm: ${{ matrix.dsm }}
          arch: ${{ matrix.arch }}
          projects: 
            ./src/web_package_example
            ./src/ExamplePackage
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
            name: packages
            path: .spk/*.spk
            
